//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickCalendar.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class UserSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserSettings defaultInstance = ((UserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserSettings())));
        
        public static UserSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool App_IsUpgraded {
            get {
                return ((bool)(this["App_IsUpgraded"]));
            }
            set {
                this["App_IsUpgraded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CloseOnEscape {
            get {
                return ((bool)(this["CloseOnEscape"]));
            }
            set {
                this["CloseOnEscape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoadLastOpenedFileOnStartup {
            get {
                return ((bool)(this["LoadLastOpenedFileOnStartup"]));
            }
            set {
                this["LoadLastOpenedFileOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastOpenedFileName {
            get {
                return ((string)(this["LastOpenedFileName"]));
            }
            set {
                this["LastOpenedFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string ShowCalendarNameInStatusBar {
            get {
                return ((string)(this["ShowCalendarNameInStatusBar"]));
            }
            set {
                this["ShowCalendarNameInStatusBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string ShowCalendarNameInWindowTitle {
            get {
                return ((string)(this["ShowCalendarNameInWindowTitle"]));
            }
            set {
                this["ShowCalendarNameInWindowTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CalendarDetailsForm_Size {
            get {
                return ((string)(this["CalendarDetailsForm_Size"]));
            }
            set {
                this["CalendarDetailsForm_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CalendarDetailsForm_lvwDatesNotableDates_ColumnSizes {
            get {
                return ((string)(this["CalendarDetailsForm_lvwDatesNotableDates_ColumnSizes"]));
            }
            set {
                this["CalendarDetailsForm_lvwDatesNotableDates_ColumnSizes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NotableDatesGeneratorEditorForm_Size {
            get {
                return ((string)(this["NotableDatesGeneratorEditorForm_Size"]));
            }
            set {
                this["NotableDatesGeneratorEditorForm_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NotableDatesGeneratorEditorForm_lvwGeneratedDates_ColumnSizes {
            get {
                return ((string)(this["NotableDatesGeneratorEditorForm_lvwGeneratedDates_ColumnSizes"]));
            }
            set {
                this["NotableDatesGeneratorEditorForm_lvwGeneratedDates_ColumnSizes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProgramOptionsForm_lvwRawProperties_ColumnSizes {
            get {
                return ((string)(this["ProgramOptionsForm_lvwRawProperties_ColumnSizes"]));
            }
            set {
                this["ProgramOptionsForm_lvwRawProperties_ColumnSizes"] = value;
            }
        }
    }
}
